import type AssignTree from "./AssignTree.js";
import type { BinaryOperationTree, ExprTree, UnaryOperationTree } from "./ExprTree.js";
import type ForTree from "./ForTree.js";
import type IfTree from "./IfTree.js";
import type RangeTree from "./RangeTree.js";
import type ProgramTree from "./ProgramTree.js";
import type RepeatUntilTree from "./RepeatUntil.js";
import type StatListTree from "./StatListTree.js";
import type WhileTree from "./WhileTree.js";
import type IteratorTree from "./IteratorTree.js";
import type FunctionTree from "./FunctionTree.js";
import type FunctionCallTree from "./FunctionCallTree.js";
import type ArrayTree from "./ArrayTree.js";
import type { DotAccessorTree, IndexAccessorTree } from "./AccessorTree.js";
import type ObjectTree from "./ObjectTree.js";
import type KeyValueTree from "./KeyValueTree.js";
import type ReturnTree from "./ReturnTree.js";
import type BreakTree from "./BreakTree.js";
import type ContinueTree from "./ContinueTree.js";
import type SetTree from "./SetTree.js";
import type LexprTree from "./LexprTree.js";
import type LexprPartTree from "./LexprPartTree.js";
import type TupleTree from "./TupleTree.js";
import type DictPairTree from "./DictPairTree.js";
import type DictTree from "./DictTree.js";

export default interface Visitor<T> {
    visitProgram(program: ProgramTree): T;
    visitAssign(assign: AssignTree): T;
    visitExpr(expr: ExprTree): T;
    visitBinary(expr: BinaryOperationTree): T;
    visitUnary(expr: UnaryOperationTree): T;
    visitStatlist(expr: StatListTree): T;
    visitWhile(expr: WhileTree): T;
    visitRepeat(expr: RepeatUntilTree): T;
    visitIf(expr: IfTree): T;
    visitFor(expr: ForTree): T;
    visitIterator(expr: IteratorTree): T;
    visitRange(expr: RangeTree): T;
    visitFunction(expr: FunctionTree): T;
    visitFunctionCall(expr: FunctionCallTree): T;
    visitArray(expr: ArrayTree): T;
    visitTuple(expr: TupleTree): T;
    visitSet(expr: SetTree): T;
    visitLexpr(expr: LexprTree): T;
    visitLexprPart(expr: LexprPartTree): T;
    visitIndex(expr: IndexAccessorTree): T;
    visitDotName(expr: DotAccessorTree): T;
    visitObject(expr: ObjectTree): T;
    visitKeyValue(expr: KeyValueTree): T;
    visitReturn(expr: ReturnTree): T;
    visitBreak(expr: BreakTree): T;
    visitContinue(expr: ContinueTree): T;
    visitDictPair(expr: DictPairTree): T;
    visitDict(expr: DictTree): T;
}